name: Example
on: [push, workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avaines/blog_gh_sha_pinning_action@465f0de6b799d33f256ab62c8e5b03032120bfe2 #1.0.1
